source 'http://rubygems.org'

gem 'rails', '3.0.7'
gem 'sqlite3'
gem 'jquery-rails', '>= 0.2.6'

group :test do
  gem 'cucumber', '0.10.0'
  gem 'cucumber-rails'
  gem 'capybara'
  gem 'launchy'
#  gem 'capybara-webkit'
  # gem 'capybara-zombie', :git => "https://github.com/plataformatec/capybara-zombie.git"
  gem 'database_cleaner'
end

group :development, :test do
  gem "ruby-debug", :platforms => :mri_18
  gem "ruby-debug19", :platforms => :mri_19
end
