source 'http://rubygems.org'

gem 'rails', '3.0.7'
gem 'sqlite3'

group :test do
  gem 'cucumber', '0.10.0'
  gem 'cucumber-rails'
  gem 'capybara'
  gem 'capybara-webkit'
  # gem 'capybara-zombie', :git => "https://github.com/plataformatec/capybara-zombie.git"
  gem 'database_cleaner'
end
